name: ItemNamer
main: com.example.itemnamer.ItemNamerPlugin
version: 1.0
api-version: "1.20"
commands:
  name:
    description: Rename the item in a player's main hand.
    usage: /name <player> <new name>
permissions:
  itemname.use:
    description: Allows using /name to rename items.
    default: op
